# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlrkxLP3Mz5_4LDliAFANfS0WILi9wUP
"""



import numpy as np
class queue:
  def _init_(self):
    self.element=np.arrange(1)
  def enqueue():
    x=np.append(self.element,data)
    return x
  def dequeue(self):
    self.np.list.pop
  def rear(self):
    return self.np.list[-1]
  def front(self):
    return self.np.list[0]
  def isempty(self):
    return (len(self.np.list)==0)
  def lenght(self):
    return len(self.np.list)

q = queue()

q.enqueue(12)

